name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Replace 404 page
        run: mv /build/errors/404.html /build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: pages
          commit-message: Github Actions build and deploy
          clean-exclude: |
            CNAME
            .nojekyll
            .gitlab-ci.yml
